### ISSUE TITLE
createsuperuser resulted in error

### ISSUE THREAD

**Issue by Ujjawal-Anand** [yasintoy/Vecihi#3]
I ran into issue 'TypeError: create_superuser() takes at least 5 arguments (4 given)' while creating a superuser by command $ ./manage.py createsuperuser
Any idea what's wrong?

**Comment by developertqw2017** [comment]
![image](https://user-images.githubusercontent.com/25227859/43236610-a91233c4-90b8-11e8-9d13-a0f0c8bdc660.png)
Vecihi/Backend/vecihi/users/models.py Class AccountManager  ，

你需需要指定一个默认参数值
You need to specify a default parameter  value
